export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const ACTOR_ROUTE = '/actor'
export const FILM_ROUTE = '/film'
export const POSTS_ROUTE = '/posts'
export const MOVIES_ROUTE = '/myMovies'